services:
  invoices-pg: 
    image: postgres:16
    ports:
      - "5483:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: invoices
    volumes:
      - ./docker:/docker-entrypoint-initdb.d